---
# File: main.yml
# Type: task
# Part: OpenVPN

## Install
- include: install-arm.yml
  when: ansible_architecture == 'armv6l' or ansible_architecture == 'armv7l'
- include: install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Configure client / server
- debug: msg="Config is {{ openvpn_config }}"
  when: openvpn_config is defined
- name: OpenVPN | Load configuration defaults
  include_vars: "vars/openvpn/{{ openvpn_config }}/main.yml"
  when: openvpn_config is defined
- name: OpenVPN | Configure client
  include: configure-client.yml
  when: openvpn_config is defined and openvpn_type == 'client'
- name: OpenVPN | Configure server
  include: configure-server.yml
  when: openvpn_config is defined and openvpn_type == 'server'

## Configure service
- include: configure-systemd.yml
  when: not docker and ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 16
- include: configure-upstart.yml
  when: not docker and ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 14
- include: configure-supervisor.yml
  when: docker

## Configure monit
- name: OpenVPN | Configure monit (useless since systemd)
  include: configure-monit.yml
  when: not docker and openvpn_monit and ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 14
